### ISSUE TITLE
B服可以解锁60帧，但是切换场景（比如进入圣遗物副本）后自定义锁帧会失效，会飙到最高帧率无法控制

### ISSUE THREAD

**Issue by LeeKaMing** [winTEuser/Genshin_StarRail_fps_unlocker#1]
[genshin-fps-unlock](https://github.com/xiaonian233/genshin-fps-unlock) 顺着大神在issue的回复找过来的，使用了一下此项目，B服能解锁60帧了，但是过段时间以后自定义锁帧也会失效，一直以最高帧率运行

启动游戏时命令行界面出现的提示：
Read Fps Fail! Error_code: 0x5

**Comment by winTEuser** [comment]
自定义的帧率在45帧的档位，完全保护后解锁器就可以关掉了，此时游戏的帧数设置已经被替换，详细在readme里有写

**Comment by jzfzzzz** [comment]
> [genshin-fps-unlock](https://github.com/xiaonian233/genshin-fps-unlock) 顺着大神在issue的回复找过来的，使用了一下此项目，B服能解锁60帧了，但是过段时间以后自定义锁帧也会失效，一直以最高帧率运行
> 
> 启动游戏时命令行界面出现的提示： Read Fps Fail! Error_code: 0x5

我的也是这样！！

**Comment by huaweitianxuan** [comment]
问题解决了没
