### ISSUE TITLE
请问可否添加一个跟随游戏关闭同时关闭工具的功能

### ISSUE THREAD

**Issue by foxhui** [winTEuser/Genshin_StarRail_fps_unlocker#12]
可否添加在游戏关闭后，同时将工具关闭的功能，现在有这个启动参数直接启动游戏，如果可以同时关闭就可以达到无感的体验了

**Comment by winTEuser** [comment]
下最新的试试

**Comment by foxhui** [comment]
> 下最新的试试

感谢，已star

**Comment by foxhui** [comment]
> 下最新的试试

您好，新版本在热补丁模式下会有一个报错弹窗，我记得这个报错在255版本是在日志中，弹窗在弹出时工具不会跟随游戏关闭，这个报错不会影响对游戏帧率的修改，一切功能正常
![image](https://github.com/user-attachments/assets/6d7b17cd-503c-4c0c-a6c4-5b265ad831a8)
