### ISSUE TITLE
是否计划支持绝区零（MobileUI）

### ISSUE THREAD

**Issue by YifePlayte** [winTEuser/Genshin_StarRail_fps_unlocker#15]
如题

**Comment by winTEuser** [comment]
之后看看，

**Comment by winTEuser** [comment]
看了一下，zzz原生就解锁了触摸输入，但有bug，这个得向官方反馈

**Comment by YifePlayte** [comment]
@winTEuser 官方现已推出《云·绝区零》，根据其登陆前右下角版本水印可知基于Win版本，或许触摸问题被解决，是否可以再次尝试支持MobileUI？

**Comment by winTEuser** [comment]
> @winTEuser 官方现已推出《云·绝区零》，根据其登陆前右下角版本水印可知基于Win版本，或许触摸问题被解决，是否可以再次尝试支持MobileUI？

牡蛎莫牡蛎
