### ISSUE TITLE
read target_fps fail

### ISSUE THREAD

**Issue by wanghao-create** [winTEuser/Genshin_StarRail_fps_unlocker#18]
每当我启动时都会弹出报错窗口read target_fps fail，但是不影响实际功能和使用

**Comment by winTEuser** [comment]
配置文件里面有EnableErrorMsg可以關掉

**Comment by jswljzy** [comment]
能否再详细地说明解决办法呢，我近期也出现了这样的情况

**Comment by winTEuser** [comment]
如果开了(ishotpatch)在配置文件里，就可以无视，如果不想再看到保错，请把配置文件里的(EnableErrorMsg)关了



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 27, 2024 07:40 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [winTEuser/Genshin_StarRail_fps_unlocker] read target_fps fail(Issue #18)




 
能否再详细地说明解决办法呢，我近期也出现了这样的情况

**Comment by jswljzy** [comment]
> 如果开了（ishotpatch）在配置文件里，就可以无视，如果不想再看到报错，请把配置文件里的（EnableErrorMsg）关了
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 27, 2024 07:40 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [winTEuser/Genshin_StarRail_fps_unlocker] read target_fps fail(Issue #18) 能否再详细地说明解决办法呢，我近期也出现了这样的情况 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

已经解决啦,谢谢
