### ISSUE TITLE
【BUG】软件启动崩铁后报错退出

### ISSUE THREAD

**Issue by bakashigure** [winTEuser/Genshin_StarRail_fps_unlocker#19]
复现：管理员权限启动软件，软件自动启动崩铁后，弹以下错误框，游戏帧数未被修改。
尝试删除配置文件重新启动，仍然报错，昨天下载使用是正常的，今天开始就不能用了。

![image](https://github.com/user-attachments/assets/9c89e156-4384-4c0f-978f-20f803624924)

**Comment by winTEuser** [comment]
用这个看看什么情况
[unlockfps_debug.zip](https://github.com/user-attachments/files/16465539/unlockfps_debug.zip)

**Comment by bakashigure** [comment]
现在均能正常使用了，删除配置文件重新启动也无法复现异常。。。
![image](https://github.com/user-attachments/assets/01222a00-2c95-4131-842b-ca102bd9b2a1)
![image](https://github.com/user-attachments/assets/82eb3443-108d-4745-bf5e-9f8e2245e2b2)
