### ISSUE TITLE
能不能将软件的图标换成原神和崩铁的图标，这也看着才不突兀

### ISSUE THREAD

**Issue by DeepClusteringLover** [winTEuser/Genshin_StarRail_fps_unlocker#2]
就是可以做两个版本，使用不同的图标

**Comment by winTEuser** [comment]
给软件创建快捷方式，快捷方式改图标

**Comment by foxhui** [comment]
可以为这个工具创建一个快捷方式，然后右键属性，点更换图标
![image](https://github.com/user-attachments/assets/c61730a8-d116-46a1-9e37-b841bbe79c99)
然后在这里选择游戏的主程序应用图标就可以了
![image](https://github.com/user-attachments/assets/fb4ab8bb-bdb4-4c59-b6b0-a57dec7179a3)

**Comment by Burger-Killer** [comment]
请问一下，如何在退出游戏时自动关闭它。我将它加入了UAC白名单，然后通过UU加速器设置路径启动它。但是当我第二次通过UU启动它时，它就会报错“已经有一个正在运行中”，我希望在我退出游戏时自动退出fps_unlocker，请问有什么途径可以设置吗？
