### ISSUE TITLE
星穹铁道2.6版手机端UI启用失败

### ISSUE THREAD

**Issue by pbxs666** [winTEuser/Genshin_StarRail_fps_unlocker#22]
会弹出如下报错（依次出现）：
![1](https://github.com/user-attachments/assets/ac99ec0b-4f52-4be1-ab05-3c6b337365a9)
![2](https://github.com/user-attachments/assets/de78aedd-21d7-416f-a23d-b2fd83225b67)
![3](https://github.com/user-attachments/assets/7fd72e4f-d2b4-4745-bbcd-8861b5e0500f)

Unlocker在星穹铁道2.5版本时可正常使用，2.6版就这样了。
用适配游戏2.6的Unlocker 2.7.9版测试下来解锁帧数可用，但手机端UI启用失败。

**Comment by winTEuser** [comment]
try this
[Uploading Unlocker_280.zip…]()

**Comment by winTEuser** [comment]
> > try this Uploading Unlocker_280.zip…
> 
> 这个文件没有上传成功，链接指向的是当前页面地址

发到release里了
