### ISSUE TITLE
解帧导致锅巴，种子和结晶异常消失

### ISSUE THREAD

**Issue by steve686** [winTEuser/Genshin_StarRail_fps_unlocker#3]
锅巴bug演示视频： https://www.bilibili.com/video/BV1RE421P7LB/?share_source=copy_web&vd_source=b671904eb42f6665bb0ffd668c8f6e61

**Comment by winTEuser** [comment]
无法复现，且应该上报官方

**Comment by SCPNVIDIA** [comment]
必须把游戏内帧率调成45，就是相当于把帧率设置成解锁器里的帧数设置才能避免这个bug

**Comment by winTEuser** [comment]
成功复现，一会儿打个补丁

**Comment by winTEuser** [comment]
试试补丁应该没这个问题了

**Comment by JosephJostar0** [comment]
> 试试补丁应该没这个问题了

玩了30min没发现问题，谢谢大佬
