### ISSUE TITLE
全屏窗口化设置问题

### ISSUE THREAD

**Issue by xcxcxx** [winTEuser/Genshin_StarRail_fps_unlocker#4]
![1](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/173567913/1cc45c83-676f-4d6a-968d-9ad83ea6119f)
![2](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/173567913/f8a8a6e5-0b5a-4c96-bce1-bec9b96b11e6)
全屏窗口化设置失败 麻烦帮看看是什么地方设置不对吗？

**Comment by winTEuser** [comment]
第一个参数是启动的游戏 并且是固定的 后面是给游戏的参数

**Comment by xcxcxx** [comment]
![4](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/173567913/582e1a7b-e7a2-4217-a37e-aa1889079635)
Alt+Tab切换程序后窗口还是会最小化

**Comment by winTEuser** [comment]
程序员偷懒没绑定命令行设置，得在游戏里设置，需要向官方反映这个问题
