### ISSUE TITLE
4.7更新以后各种闪退蓝屏。

### ISSUE THREAD

**Issue by xitiaowuyi** [winTEuser/Genshin_StarRail_fps_unlocker#5]
When our game crashes, we restart the game and the next time we play it, we get a blue screen. Blue screen code D1, 4E, various, blue screen process yuanshen.exe

**Comment by xitiaowuyi** [comment]
When our game crashes, we restart the game and the next time we play it, we get a blue screen. Blue screen code D1, 4E, various, blue screen process yuanshen.exe
![屏幕截图 2024-06-26 042747](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/43715256/afc210a1-d76c-40a5-8fed-36525566c1d4)

**Comment by winTEuser** [comment]
try replace a good memory bar?

**Comment by winTEuser** [comment]
try replace a good memory bar?

**Comment by winTEuser** [comment]
try replace a good memory bar?
