### ISSUE TITLE
窗口里弹出一行错误

### ISSUE THREAD

**Issue by hudong2002** [winTEuser/Genshin_StarRail_fps_unlocker#6]
![QQ截图20240626214322](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/74283982/6cc0719b-d8d1-4a25-a390-7006f557bc93)

**Comment by hudong2002** [comment]
麻烦帮忙看看是什么问题，谢谢了

**Comment by winTEuser** [comment]
被驱动挡了，不是大问题，之后会有beta版来尝试解决这个问题
