### ISSUE TITLE
The Genshin Impact app crashes

### ISSUE THREAD

**Issue by xitiaowuyi** [winTEuser/Genshin_StarRail_fps_unlocker#8]
Let’s ignore the blue screen issue, it seems to be caused by my overclocking.
Currently, the main problem is that the Genshin Impact app crashes. I idle all night and found that the app closed automatically when I woke up in the morning.

**Comment by winTEuser** [comment]
Please provide relevant logs or screenshots to locate bug

如果英文不方便请用中文，崩溃需要确切的日志/截图才好定位

**Comment by xitiaowuyi** [comment]
日志在哪里你生成的日志，崩溃系统log是没有的，直接原神消失了

> 请提供相关日志或者截图以便定位bug
> 
> 如果英文不方便请用中文，失败需要被判处死刑/截图才好定位

**Comment by xitiaowuyi** [comment]
还有一个问题原神帧率无法限制固定值，怎么弄都是最大值。如图
![Uploading 屏幕截图 2024-06-27 041301.png…]()

**Comment by xitiaowuyi** [comment]
目前我刚安装RivaTuner Statistics Server才把帧率限制到90，或120帧
![Uploading 屏幕截图 2024-06-27 041413.png…]()

**Comment by xitiaowuyi** [comment]
![Uploading 屏幕截图 2024-06-27 041301.png…]()

**Comment by winTEuser** [comment]
看不到你发的图片，还有这个帧率无限制的问题置顶issue就提过，在游戏里设置为45帧就走你设置的帧率

**Comment by xitiaowuyi** [comment]
我观察闪退，偶尔启动游戏玩不到几分钟就闪退。

**Comment by winTEuser** [comment]
不开解锁器启动也崩溃？

**Comment by xitiaowuyi** [comment]
不是 开启解锁，不开启闪退没有出现，还有-EnableMobileUI在配置文件加入？怎么加入有示例么
[Setting]
GenshinPath=D:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe
HKSRPath=
IsAntiMisscontact=0
IsHotpatch=1
TargetDevice=2
FPS=90

**Comment by winTEuser** [comment]
> 不是 开启解锁，不开启闪退没有出现，还有-EnableMobileUI在配置文件加入？怎么加入有示例么 [Setting] GenshinPath=D:\Program Files\Genshin Impact\Genshin Impact Game\YuanShen.exe HKSRPath= IsAntiMisscontact=0 IsHotpatch=1 TargetDevice=2 FPS=90

命令行或快捷方式 第二个参数
unlocker.exe -Genshin -EnableMobileUI -其他参数...

**Comment by xitiaowuyi** [comment]
最后还有不懂的启动后能否关闭命令行窗口

**Comment by winTEuser** [comment]
> 最后还有不懂的启动后能否关闭命令行窗口

关了就调节不了，可以关
