### ISSUE TITLE
原神自动闪退，重新上传图

### ISSUE THREAD

**Issue by xitiaowuyi** [winTEuser/Genshin_StarRail_fps_unlocker#9]
![屏幕截图 2024-06-27 055651](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/43715256/7e753c8d-efab-48ef-b603-c17c631d876e)
![屏幕截图 2024-06-27 055712](https://github.com/winTEuser/Genshin_StarRail_fps_unlocker/assets/43715256/71d9d142-714c-44ad-993f-a56abf3d00db)

**Comment by xitiaowuyi** [comment]
闪退后，游戏加加会弹出来，系统没有任何LOG记录，我查看原神目录的LOGS目录也没有，游戏加加记录1小时2分钟。

**Comment by winTEuser** [comment]
只能建议先排查下硬件故障

**Comment by winTEuser** [comment]
有跑过稳定性压力测试吗

**Comment by xitiaowuyi** [comment]
3D跑分各项都过，13600KF,32G 7200MHZ,6900GRE，我天天玩STEAM的游戏，现在不解除帧测试中。挂机玩WOW

**Comment by winTEuser** [comment]
3dmark压力测试，还有fpu，完了还有内存都测一遍

**Comment by xitiaowuyi** [comment]
好。

**Comment by xitiaowuyi** [comment]
已经解决软件冲突，貌似，卸载一堆软件好了。还有一个事能否有隐藏参数，启动直接原神不提示是否选择崩铁和原神

**Comment by winTEuser** [comment]
> 已经解决软件冲突，貌似，卸载一堆软件好了。还有一个事能否有隐藏参数，启动直接原神不提示是否选择崩铁和原神

readme有写

**Comment by xitiaowuyi** [comment]
找到了 -原神  对了 最新版本2.6.1 读取帧会报错拒绝访问？Read Target_fps Fail! ( 0x5 ) - 拒绝访问。

**Comment by winTEuser** [comment]
> 找到了 -原神 对了 最新版本2.6.1 读取帧会报错拒绝访问？Read Target_fps Fail! ( 0x5 ) - 拒绝访问。

正常，无视即可
